a="Aayu  shiz  zzzzz"
print(a)
print(len(a))
print(a.rstrip("z"))
print(a.upper())
print(a.lower())
print(a.format())
print(a.replace("Aayushi","Anishka"))
#strings are immutable in nature we canot change the value but we can modify it every time changed strimng will re created in memory
print(a.split(" "))
heading="introduction to heading my a"
print(heading.capitalize())
print(a.casefold())
print(a.encode())
print(heading.center(20))
print(a.count("Aaysuhi"))
print(a.endswith("z"))
print(len(a))
name="77777 b  welcome"
print(name.endswith("the",6,12))
print(name.find("the"))
# print(name.index("hell"))
print(name.isalnum())
print(name.isalpha())
print(name.islower())
print(name.isprintable())
a="    "
print(a.isspace())
print(name.istitle())
print(name.startswith("A"))
print(name.swapcase())
print(name.title())